### ISSUE TITLE
Deleting

### ISSUE THREAD

**Issue by Stacxzzzz** [Linkin-Lab-Server/litematica#1]
On the 1.19 litematica version, when i try to delete chunks, it instead just types the command into chat over and over, instead of actually deleting the chunks.
![2022-06-15_11 09 33](https://user-images.githubusercontent.com/107570010/173874850-ac6b4c1f-eca3-4e57-9fce-b6f4ad2a7241.png)

**Comment by plusls** [comment]
fixed
