### ISSUE TITLE
update to 1.19.1

### ISSUE THREAD

**Issue by ghost** [Linkin-Lab-Server/litematica#13]
Also provide support for malilib 0.13.0

**Comment by WojtekPlay** [comment]
mmmm yes please

**Comment by fungoza** [comment]
1. Download mod
2. Open as Zip-archive
3. Open fabric.mod.json
4. Replace 0.12.x to 0.13.x in end of file

**Comment by jacobjdavis** [comment]
I'm still getting an error when doing this: 
`Internal Exception: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_634 failed`.

I am running the 1.19.1 fabric client and I have the 1.19.1 malilib mod.

@FurnyGo

**Comment by ghost** [comment]
> 1. Download mod
> 2. Open as Zip-archive
> 3. Open fabric.mod.json
> 4. Replace 0.12.x to 0.13.x in end of file

I have done this before but it crashes on launch.

**Comment by SemGamerNL** [comment]
> 

Same
