### ISSUE TITLE
Pasting is broken on servers and experiences significant FPS drop when "pasting"

### ISSUE THREAD

**Issue by AllOutJay** [Linkin-Lab-Server/litematica#2]
**Minecraft version:** 
Minecraft 1.19

**Mod Version and Malilib Version:** 
litematica-fabric-1.19-0.11.2.jar + malilib-fabric-1.19-0.12.1.jar + fabric-api-0.56.0+1.19.jar (all other mods were removed in a different test not in the YouTube link)

**Description of the issue:** 
When trying to paste any schematic on a server, the operation will execute saying it is pasting/filling the chunks when in reality it doesn't actually paste it. This happens on a fresh vanilla server or a paper server too. My FPS also appears to spike down dramatically when the operation is "executing". Here is also a [link to a video showing the issues](https://www.youtube.com/watch?v=I3CpI0wu5Ko).

**Comment by fantahund** [comment]
Fixed https://github.com/Linkin-Lab-Server/litematica/pull/3

**Comment by Stacxzzzz** [comment]
you have fixed this problem?

**Comment by fantahund** [comment]
Yes I also sent a pull request. ^^ --> https://github.com/Linkin-Lab-Server/litematica/pull/3

**Comment by plusls** [comment]
fixed
